server:
  port: 8080
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
  datasource:
    url: jdbc:mysql://localhost:3306/xurongtest
    password: xr10317139
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
